keys:
  - &admin_rhodate age1ujlyknmj9w8urr4cqsxry09scrtcx2auj7n057mvtaa835f2m3tspy5ryu
  - &server_chito age1c6p58sg90tu0x90ku3xzegfncyvm0wq73ftta0eday6vy7alkajsw975cg
creation_rules:
  - path_regex: secrets/common/[^/]+$
    key_groups:
      - age:
        - *admin_rhodate
        - *server_chito
  - path_regex: secrets/management/[^/]+$
    key_groups:
      - age:
        - *admin_rhodate
  - path_regex: secrets/syncthing/[^/]+$
    key_groups:
      - age:
        - *admin_rhodate
  - path_regex: secrets/server/.+$
    key_groups:
      - age:
        - *server_chito
